#core:
#  connections:
#    - name: ccpPath
#      value: yellow
#    - name: walletPath
#      color: red
#  users:
#    - name: mint
#      value: minter
core:
  config:
    activate:
      on-profile: test
  connections:
    - ccp-name: org1ccp
      ccp-path: "/Users/mjkong/mym-crypto/organizations/peerOrganizations/org1.example.com/connection-org1.json"
    - ccp-name: org2ccp
      ccp-path: "/Users/mjkong/mym-crypto/organizations/peerOrganizations/org2.example.com/connection-org2.json"
  users:
    - name: minter
      organization: org1
      mspid: Org1MSP
      id: minter@org1.example.com
      role: minter
      credential-root: "/Users/mjkong/mym-crypto/organizations/peerOrganizations/org1.example.com/users"
      wallet-root: "/Users/mjkong/mym-crypto/wallet"
  erc721:
    channel: mychannel
    ccn: token_erc721
  erc20:
    channel: mychannel
    ccn: token_erc20

spring:
  data:
    mongodb:
      host: 192.168.56.2
      port: 27017
      authentication-database: admin
      username: mymb
      password: mymb
      database: mymb_pom